id: I407FD42D
legacy_id: P000534
ocr_import_info:
  bdrc_scan_id: W1KG9751
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:52:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:38:05.309835+00:00'
last_modified: 2022-09-01 02:38:18.911380
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9751
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9751
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞྭ་ལུའི་ཆོས་སྤྱོད།
  author: ཞྭ་ལུ་རི་ཕུག
statistics:
  ocr_word_mean_confidence_index: 0.8232155671076287
  ocr_word_median_confidence_index: 0.8999999761581421
quality: null
bases:
  I1KG9764:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9764
      total_pages: 426
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9764.txt
    statistics:
      ocr_word_median_confidence_index: 0.8999999761581421
      ocr_word_mean_confidence_index: 0.8232155671076287
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
