id: P000534
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9751
  title: ཞྭ་ལུའི་ཆོས་སྤྱོད།
  author: ''
  volumes:
    7494f85b3717442d83d3d17e1fa9f2b0:
      image_group_id: I1KG9764
      title: Volume 1 of zhwa lu'i chos spyod/
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
